// Demo articles for seeding the database on first run
export const DEMO_ARTICLES = [
  {
    slug: 'ghid-complet-paris-7-zile',
    title: 'Ghid complet pentru Paris în 7 zile: tot ce trebuie să știi',
    excerpt: 'De la Turnul Eiffel la cafenele ascunse în Le Marais – un itinerar testat și toate sfaturile de care ai nevoie pentru o săptămână perfectă în Orașul Luminilor.',
    cover: 'https://images.pexels.com/photos/618752/pexels-photo-618752.jpeg',
    continent: 'Europa',
    country: 'Franța',
    city: 'Paris',
    type: 'City Break',
    tags: ['Paris', 'Europa', 'City Break', 'Cultură'],
    readingMinutes: 12,
    featured: true,
    author: 'Andrei Munteanu',
    intro: "Parisul nu se vede într-o zi – și nici măcar într-o săptămână, dacă e să fim sinceri. Dar 7 zile sunt suficiente să prinzi sufletul orașului: croissant-uri calde dimineața, plimbări pe malul Senei la apus, muzee care ți se lipesc de inimă. În acest ghid âți arăt exact ce am făcut în ultima mea călătorie, cât am cheltuit și ce aș fi schimbat.\n\nDacă e prima ta dată în Paris, prioritizează cele 3 zile centrale (zilele 1-3) și adaugă zilele tematice după preferințe. La final găsești și un buget detaliat și un mini-dicționar de fraze utile.",
    whenToVisit: 'Cele mai bune perioade sunt aprilie-iunie și septembrie-octombrie, când vremea e blândă și aglomerația mai mică decât vara. Iulie și august sunt scumpe și extrem de aglomerate, dar Parisul are un farmec aparte vara târziu, când parizienii pleacă în vacanță. Decembrie aduce pieețe de Crăciun magice în Champs-Élysées.',
    budget: 'Buget mediu pentru 7 zile, două persoane: \u00ac1.450-2.100 €. Cazare 3* centrală: 110-160 €/noapte. Masă la bistro: 18-28 € de persoană. Transport public (Navigo): 30 € săptămânal. Muzee: 14-22 €. Recomand Paris Museum Pass de 4 zile (78 €) dacă vrei mai mult de 3 muzee.',
    transport: 'Aeroporturile CDG și Orly sunt conectate prin RER B/C cu centrul (12 €, 35-50 min). În oraș, metroul are 16 linii și acoperă tot. Aplicația oficială „Bonjour RATP” e excelentă. Bicicletele Vélib pe maluri (1 € pentru 24h cu zona Free) sunt magice la apus.',
    accommodation: 'Recomand cartierele Le Marais (3-4), Saint-Germain (6) sau Montmartre (18) pentru atmosferă. Hôtel Jeanne d’Arc – boutique 3* în Marais (120 €/noapte), Generator Paris – hostel design pentru bugete mici (35 €/pat). Evită zona Gâre du Nord seara.',
    attractions: [
      { name: 'Turnul Eiffel', description: 'Mergi la apus pentru fotografii și așteaptă ora când se iluminează – 5 minute, la fiecare oră.' },
      { name: 'Muzeul Luvru', description: 'Intră prin Carrousel du Louvre (mai puțină coadă) și începe cu Denon. Bilete online obligatoriu.' },
      { name: 'Catedrala Notre-Dame', description: 'Redeschisă în decembrie 2024 după restaurare. Cea mai impresionantă priveliște e de pe Pont de l’Archevêché.' },
      { name: 'Montmartre & Sacré-Cœur', description: 'Urcă pe jos, evită funicularul aglomerat. La apus, vederea peste Paris e fără cuvinte.' },
      { name: 'Muzeul d’Orsay', description: 'Impresioniștii – Monet, Van Gogh, Renoir – într-o fostă gară spectaculoasă. Vinerea seara, deschis până la 21:45.' },
    ],
    restaurants: [
      { name: 'Bouillon Pigalle', description: 'Mâncare franțuzească clasică la 12-15 € felul. Atmosferă autentică, fară rezervare.' },
      { name: 'Du Pain et des Idées', description: 'Cea mai bună boulangerie din Paris. Escargot la pistache obligatoriu.' },
      { name: 'Clóver Grill', description: 'Pentru o seară mai specială – carne perfect gătită, ambianță modernă.' },
    ],
    tips: [
      'Cumpără bilete la atracții cu 2-3 săptămâni înainte; cele de zi se epuizează.',
      'Pașii zilnici vor fi 15.000+ – încalțați-vă confortabil.',
      'Restaurantele își închid bucătăria între 14:30-19:00. Planifică mesele.',
      'Învață câteva fraze în franceză – „bonjour” și „merci” deschid uși închise.',
      'Atacă muzeele mari dimineața devreme (deschidere) sau cu o oră înainte de închidere.',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1502602898657-3e91760cbb34?w=1600',
      'https://images.unsplash.com/photo-1431274172761-fca41d930114?w=1600',
      'https://images.unsplash.com/photo-1499856871958-5b9627545d1a?w=1600',
      'https://images.unsplash.com/photo-1520939817895-060bdaf4fe1b?w=1600',
    ],
    publishedAt: '2025-05-20',
  },
  {
    slug: 'bali-itinerar-10-zile-paradisul-asiei',
    title: 'Bali în 10 zile: itinerar complet prin paradisul Asiei',
    excerpt: 'Orezarii în terase, temple ascunse, plaje cu nisip negru și cele mai bune spoturi pentru sunset. Un itinerar testat care îți arată celălalt Bali.',
    cover: 'https://images.unsplash.com/photo-1539367628448-4bc5c9d171c8',
    continent: 'Asia',
    country: 'Indonezia',
    city: 'Bali',
    type: 'Aventură',
    tags: ['Bali', 'Asia', 'Plajă', 'Aventură'],
    readingMinutes: 15,
    featured: true,
    author: 'Andrei Munteanu',
    intro: "Bali e mai mult decât cartelele poștale de pe Instagram. E un loc unde diminețele încep cu rugăciuni în temple, câinii dorm pe drum și un smântânos smântânos de mango costă 50 de cenți. În acest itinerar de 10 zile combinaqm cultură (Ubud), aventură (Munduk și Sidemen) și plajă (Uluwatu și Nusa Penida).",
    whenToVisit: 'Sezonul uscat aprilie-octombrie e ideal. Vrei mai puțini turiști? Mai și septembrie sunt sweet spot-uri – vreme bună, prețuri rezonabile.',
    budget: '10 zile, două persoane: 900-1.500 € (fără zborul internațional). Villa cu piscină privată: 35-70 €/noapte. Mâncare locală (warungs): 1.50-3 € felul. Scooter: 4-6 €/zi.',
    transport: "Zborurile spre Denpasar (DPS) până în 700 €. În Bali: scooter (carnet internațional!) sau șofer privat 35 €/zi pentru excursii. Grab și Gojek pentru distanțe scurte.",
    accommodation: 'Ubud: Suarapala Suites (45 €). Munduk: Munduk Moding Plantation (panoră cu munți). Uluwatu: Mu Bungalows. În Nusa Penida – The Tamarind House.',
    attractions: [
      { name: 'Terasele de orez Tegallalang', description: 'Mergi dimineața devreme (înainte de 8:00) ca să prinzi lumina aurie fără mulțime.' },
      { name: 'Templul Tirta Empul', description: 'Ritual de purificare în ape sacre. Închiriază sarong și intră cu respect.' },
      { name: 'Cascada Sekumpul', description: 'Cea mai spectaculoasă cascadă din Bali, trek 45 min prin junglă.' },
      { name: 'Templul Uluwatu', description: 'Apusul și Kecak Fire Dance – unul dintre cele mai magice momente din Bali.' },
      { name: 'Nusa Penida (Kelingking Beach)', description: 'Excursie de o zi cu speedboat de la Sanur. „T-Rex Beach” e iconică.' },
    ],
    restaurants: [
      { name: 'Warung Babi Guling Ibu Oka (Ubud)', description: 'Faimosul porc fript balinez. Cer-l cu porție completă.' },
      { name: 'La Brisa (Canggu)', description: 'Beach club cu vibe magic pentru sunset și cocktail-uri.' },
      { name: 'Locavore Community (Ubud)', description: 'Fine dining cu ingrediente locale – experiență de neuitat.' },
    ],
    tips: [
      'Cumpără SIM cu date pe aeroport (Telkomsel) – acoperire excelentă.',
      'Maimuțele din Sacred Monkey Forest fură ochelari – lasă-i în rucsac.',
      'Negociază pe piață, dar nu agresiv – 30-40% reducere e normal.',
      'Apa de la robinet – doar pentru duș, niciodată băut.',
      'Casca pe scooter – obligatorie și pentru pasager.',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1537996194471-e657df975ab4?w=1600',
      'https://images.unsplash.com/photo-1518548419970-58e3b4079ab2?w=1600',
      'https://images.unsplash.com/photo-1604999333679-b86d54738315?w=1600',
      'https://images.unsplash.com/photo-1554481923-a6918bd997bc?w=1600',
    ],
    publishedAt: '2025-04-15',
  },
  {
    slug: 'tokyo-pentru-prima-data-ghid-7-zile',
    title: 'Tokyo pentru prima dată: ghid de 7 zile prin metropola viitorului',
    excerpt: 'Cum să înțelegi Tokyo în doar o săptămână – cartiere, sushi, temple și culturi care se ciocnesc perfect.',
    cover: 'https://images.unsplash.com/photo-1542051841857-5f90071e7989',
    continent: 'Asia',
    country: 'Japonia',
    city: 'Tokyo',
    type: 'City Break',
    tags: ['Tokyo', 'Japonia', 'Asia', 'Cultură'],
    readingMinutes: 14,
    featured: true,
    author: 'Andrei Munteanu',
    intro: "Tokyo nu e un oraș – e o constelație de orașe suprapuse. Fiecare cartier are propria personalitate, propria masă și propriul ritm. În 7 zile poți prinde esența dacă ești strategic.",
    whenToVisit: 'Martie-aprilie pentru sakura, octombrie-noiembrie pentru frunzele toamnei. Evită august (extrem de umed).',
    budget: '7 zile, două persoane: 1.700-2.500 €. Cazare bună: 100-150 €. Masă: 6-15 € la prânz, 25-50 € seara. Transport (Suica + JR Pass): 80 €.',
    transport: 'JR Pass de 7 zile (340 €) e merită dacă mergi și la Kyoto. Suica card e indispensabil pentru metroul din Tokyo.',
    accommodation: 'Cartiere recomandate: Shinjuku (animat), Shibuya (modern), Asakusa (tradițional). Citan Hostel, Hotel Gracery Shinjuku, Park Hyatt Tokyo.',
    attractions: [
      { name: 'Shibuya Crossing', description: 'Cel mai aglomerat trecere de pietoni din lume. Vezi-o de sus de la Shibuya Sky.' },
      { name: 'Templul Sensō-ji (Asakusa)', description: 'Cel mai vechi templu din Tokyo. Mergi seara, când e iluminat și liniștit.' },
      { name: 'Tsukiji Outer Market', description: 'Mic dejun cu sushi proaspăt la 6:30 dimineața.' },
      { name: 'TeamLab Borderless', description: 'Muzeu de artă digitală imersivă – rezervă bilete cu o lună înainte.' },
      { name: 'Cartierul Harajuku & Omotesando', description: 'Cultură pop și arhitectură modernă alături.' },
    ],
    restaurants: [
      { name: 'Ichiran Ramen', description: 'Faimosul tonkotsu ramen în cabine individuale. Experiență unică.' },
      { name: 'Sushi Saito', description: 'Pentru o experiență fine dining – rezervă cu luni înainte.' },
      { name: 'Memory Lane (Omoide Yokocho)', description: 'Yakitori și bere în aleile cu felinare roșii.' },
    ],
    tips: [
      'Cumpără Pocket WiFi sau eSIM înainte de zbor.',
      'În metrou: liniște totală, fără telefoane la ureche.',
      'Tipping NU se așteaptă – e chiar nepoliticos.',
      'Cash încă esențial în multe locuri mici.',
      '7-Eleven, FamilyMart – micul dejun bun și ieftin.',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1503899036084-c55cdd92da26?w=1600',
      'https://images.unsplash.com/photo-1554797589-7241bb691973?w=1600',
      'https://images.unsplash.com/photo-1493780474015-ba834fd0ce2f?w=1600',
      'https://images.unsplash.com/photo-1480796927426-f609979314bd?w=1600',
    ],
    publishedAt: '2025-03-10',
  },
  {
    slug: 'santorini-ghid-romantic-5-zile',
    title: 'Santorini: ghid romantic pentru 5 zile pe cea mai frumoasă insulă grecească',
    excerpt: 'Cele mai bune apusuri, sate mai puțin turistice și restaurantele cu vedere pe care nu le știe toată lumea.',
    cover: 'https://images.pexels.com/photos/15532995/pexels-photo-15532995.jpeg',
    continent: 'Europa',
    country: 'Grecia',
    city: 'Santorini',
    type: 'Romantic',
    tags: ['Santorini', 'Grecia', 'Europa', 'Insule'],
    readingMinutes: 10,
    featured: false,
    author: 'Andrei Munteanu',
    intro: 'Santorini e clichéul perfect – și merită fiecare poză. Dar dincolo de Oia există sate liniștite, plaje vulcanice și podgorii uimitoare. 5 zile sunt ideale.',
    whenToVisit: 'Mai și septembrie sunt perfecte: vreme bună, prețuri mai mici, mai puțini turiști decât în august.',
    budget: '5 zile, doi: 1.200-2.000 €. Cazare cu vedere caldera: 180-400 €/noapte.',
    transport: 'Aeroport JTR – taxi spre Fira 25 €. Pe insulă închiriază ATV (35 €/zi) sau mașină mică.',
    accommodation: 'Imerovigli pentru liniște și panoră. Pyrgos pentru autentic. Oia doar dacă vrei sunset experience.',
    attractions: [
      { name: 'Oia la apus', description: 'Mergi cu 1.5h înainte pentru un loc bun. Sau urcă pe ruinele castelului.' },
      { name: 'Akrotiri', description: '„Pompeii-ul grecesc” – oraș îngropat în lavă acum 3.500 de ani.' },
      { name: 'Red Beach & White Beach', description: 'Plaje vulcanice unice. Access by boat.' },
      { name: 'Wine tasting la Santo Wines', description: 'Vinul Vinsanto și vederea – magic.' },
    ],
    restaurants: [
      { name: 'Metaxi Mas (Exo Gonia)', description: 'Cea mai bună masă traditională din insulă. Rezervare obligatorie.' },
      { name: 'Selene (Pyrgos)', description: 'Fine dining cu vedere panoră.' },
      { name: 'Lucky’s Souvlakis (Fira)', description: 'Cea mai bună gyro pe insulă, 4 €.' },
    ],
    tips: [
      'Rezervă cazarea cu 6 luni înainte vara.',
      'Apa e scumpă – ia sticle mari de la supermarket.',
      'Pantofi confortabili pe scenările din Fira/Oia.',
      'Excursie de o zi la Thirassia – insula liniștită vis-à-vis.',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1613395877344-13d4a8e0d49e?w=1600',
      'https://images.unsplash.com/photo-1601581875309-fafbf2d3ed3a?w=1600',
      'https://images.unsplash.com/photo-1570213489059-0aac6626cade?w=1600',
    ],
    publishedAt: '2025-02-22',
  },
  {
    slug: 'new-york-72-ore-ghid-rapid',
    title: 'New York în 72 de ore: ghid rapid pentru prima vizită',
    excerpt: 'Cele mai eficiente 3 zile în Marele Măr – ce să vezi, unde să mănânci și cum să economisești.',
    cover: 'https://images.pexels.com/photos/32479340/pexels-photo-32479340.jpeg',
    continent: 'America',
    country: 'Statele Unite',
    city: 'New York',
    type: 'City Break',
    tags: ['New York', 'America', 'City Break'],
    readingMinutes: 11,
    featured: true,
    author: 'Andrei Munteanu',
    intro: 'NYC e un oraș care nu doarme – și nici tu nu ai să dormi prea mult. 72 ore sunt suficiente pentru un cool teaser, dar trebuie strategie.',
    whenToVisit: 'Aprilie-iunie și septembrie-noiembrie. Iarna e magică în decembrie (Christmas vibes), dar ger.',
    budget: '3 zile, două persoane: 1.400-2.200 €. Hotel central 4*: 250 €/noapte.',
    transport: 'JFK → Manhattan cu AirTrain + LIRR (16 €, 40 min) sau metro (11 €, 1h). În oraș: metroul (3.25 € pe călătorie) și picioarele.',
    accommodation: 'Midtown pentru prima vizită. Pod 39, citizenM Times Square, Moxy Times Square.',
    attractions: [
      { name: 'Statue of Liberty + Ellis Island', description: 'Bilete cu pedestal access. Rezervă prima fereastră a zilei.' },
      { name: 'Central Park', description: 'Bow Bridge, Bethesda Fountain, The Mall – plimbare de 2 ore.' },
      { name: 'Top of the Rock vs Empire State', description: 'Top of the Rock pentru că vezi Empire State în poză.' },
      { name: 'High Line + Chelsea Market', description: 'Plimbare pe vechi linii de cale ferată, apoi street food.' },
      { name: 'Brooklyn Bridge la apus', description: 'Pleacă din Brooklyn spre Manhattan ca să ai skyline-ul în fața.' },
    ],
    restaurants: [
      { name: 'Joe’s Pizza', description: 'Felia clasică newyorkeză, 4 €.' },
      { name: 'Katz’s Delicatessen', description: 'Pastrami sandwich-ul iconic. Mergi cu apetit.' },
      { name: 'Levain Bakery', description: 'Cele mai groase cookie din lume.' },
    ],
    tips: [
      'Cumpără New York CityPASS dacă vrei multe atracții.',
      'Tip 18-20% în restaurante – e obligatoriu cultural.',
      'Metroul merge 24/7 dar încet noaptea.',
      'Times Square e bun de văzut o dată, apoi fugi.',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1496442226666-8d4d0e62e6e9?w=1600',
      'https://images.unsplash.com/photo-1485871981521-5b1fd3805eee?w=1600',
      'https://images.unsplash.com/photo-1522083165195-3424ed129620?w=1600',
    ],
    publishedAt: '2025-01-18',
  },
  {
    slug: 'islanda-ring-road-ghid-7-zile',
    title: 'Islanda Ring Road în 7 zile: aurora, ghețari și cascade',
    excerpt: 'Un road trip prin cea mai surrealistă ară din lume. Itinerar exact, ce să împachetezi și unde să dormi.',
    cover: 'https://images.unsplash.com/photo-1529963183134-61a90db47eaf',
    continent: 'Europa',
    country: 'Islanda',
    city: 'Reykjavik',
    type: 'Aventură',
    tags: ['Islanda', 'Europa', 'Road Trip', 'Natură'],
    readingMinutes: 16,
    featured: false,
    author: 'Andrei Munteanu',
    intro: 'Islanda nu e o destinație – e o stare. La fiecare 10 km, peisajul se schimbă: câmpii de mușchi verde, vulcani fumegânzi, cascade cât un bloc.',
    whenToVisit: 'Iunie-august pentru zile lungi și acces complet. Septembrie-martie pentru aurora boreală.',
    budget: '7 zile, doi: 2.000-3.000 €. Cazare 80-150 €. Mașină 4x4: 80 €/zi. Benzină: 1.90 €/litru.',
    transport: 'Mașină absolut necesară. Recomand 4x4 dacă mergi în F-roads. Rute principale – mașină mică e suficient vara.',
    accommodation: 'Guesthouses, cabane (rotte de cottage). Booking + Airbnb. Rezervă cu 4-6 luni înainte vara.',
    attractions: [
      { name: 'Golden Circle', description: 'Thingvellir, Geysir, Gullfoss – clasicul de o zi.' },
      { name: 'Cascada Skógafoss și Seljalandsfoss', description: 'Poți merge în spatele Seljalandsfoss.' },
      { name: 'Plaja neagră Reynisfjara', description: 'Atenție la valurile ucigătoare – NU intra în apă.' },
      { name: 'Glaciar Lagoon Jökulsárlón', description: 'Iceberg-uri plutind către ocean. Magic.' },
      { name: 'Pen Îrsula Snæfellsnes', description: '„Mini-Iceland” – toate peisajele într-o zi.' },
    ],
    restaurants: [
      { name: 'Bæjarins Beztu Pylsur (Reykjavik)', description: 'Cel mai bun hot dog din lume, 4 €.' },
      { name: 'Fjallaksála', description: 'Supă de miel într-o pita – perfect după hike.' },
      { name: 'Pakkhus (Höfn)', description: 'Lobster langoustines proaspete.' },
    ],
    tips: [
      'Verifică vremea/safetravel.is zilnic.',
      'Benzina e scumpă – plin la fiecare ocazie.',
      'Apele termale – du-te la Sky Lagoon în loc de Blue Lagoon (mai puțin turistic).',
      'Aurora – instalează aplicația My Aurora Forecast.',
      'Haină impermeabilă + termică indiferent de sezon.',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1490718720478-364a07a997cd?w=1600',
      'https://images.unsplash.com/photo-1531168556467-80aace0d0144?w=1600',
      'https://images.unsplash.com/photo-1504541989296-2b0b97a40c0e?w=1600',
    ],
    publishedAt: '2024-12-10',
  },
  {
    slug: 'maldive-ghid-honeymoon-paradis',
    title: 'Maldive: ghidul ultim pentru luna de miere în paradis',
    excerpt: 'Cum alegi insula potrivită, când să mergi și cum să nu plătești dublu pentru visul tropical.',
    cover: 'https://images.pexels.com/photos/36661715/pexels-photo-36661715.jpeg',
    continent: 'Asia',
    country: 'Maldive',
    city: 'Malé',
    type: 'Romantic',
    tags: ['Maldive', 'Asia', 'Plajă', 'Honeymoon'],
    readingMinutes: 9,
    featured: false,
    author: 'Andrei Munteanu',
    intro: 'Maldivele sunt scumpe – dar nu trebuie să cheltui 10.000 € pentru o experiență magică. Cu puțină planificare, poți avea visul tropical la 3.500 € pentru doi.',
    whenToVisit: 'Decembrie-aprilie – sezon uscat, ape calme.',
    budget: '7 nopți, doi: 3.500-7.000 € (cu zbor). All-inclusive 4-5* începe de la 250 €/noapte/persoană.',
    transport: 'Sosire în Malé (MLE). Transfer cu speedboat (50-100 €) sau seaplane (350 €+).',
    accommodation: 'Recomand atolele Ari de Sud (snorkeling) sau Baa (UNESCO). Vilamendhoo, Reethi Beach, Joali Maldives pentru lux.',
    attractions: [
      { name: 'Snorkeling cu mantarays', description: 'Atolul Baa – Hanifaru Bay (iunie-noiembrie).' },
      { name: 'Cina pe plajă privătă', description: 'Cele mai bune resorts oferă „desert island dinner”.' },
      { name: 'Spa over-water', description: 'Masaj cu vederi de coral reef dedesubt.' },
      { name: 'Sandbank picnic', description: 'Excursie pe o limbă de nisip izolată.' },
    ],
    restaurants: [
      { name: 'By Symphony (Joali)', description: 'Fine dining indo-japonez.' },
      { name: '5.8 Undersea Restaurant', description: 'Mâncare gourmet sub apă.' },
      { name: 'Local dîțan gîțan (Malé)', description: 'Piața de pește – experiență autentică.' },
    ],
    tips: [
      'All-inclusive merită – băuturile la ânauție costă enorm.',
      'Salaca și sketele În masă: 22-50€ per zi.',
      'Carduri internationale, peste tot.',
      'Aplicație utilă: Google Translate cu „Dhivehi”.',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1573843981267-be1999ff37cd?w=1600',
      'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?w=1600',
      'https://images.unsplash.com/photo-1586500036706-41963de24d8b?w=1600',
    ],
    publishedAt: '2024-11-05',
  },
  {
    slug: 'roma-3-zile-itinerar-istoric',
    title: 'Roma în 3 zile: itinerar prin Imperiu și Vatican',
    excerpt: 'Colosseum, Vatican, Trastevere – toate într-un weekend bine pus la punct.',
    cover: 'https://images.pexels.com/photos/27541217/pexels-photo-27541217.jpeg',
    continent: 'Europa',
    country: 'Italia',
    city: 'Roma',
    type: 'Cultural',
    tags: ['Roma', 'Italia', 'Europa', 'Cultură', 'Istorie'],
    readingMinutes: 10,
    featured: false,
    author: 'Andrei Munteanu',
    intro: 'Roma e o lecție de istorie cu paste. În 3 zile prinzi cele 3 epoci esențiale: Imperiul (Colosseum, Forum), Renaissance (Vatican) și Roma modernă (Trastevere).',
    whenToVisit: 'Aprilie-mai, septembrie-octombrie. Iulie-august – caniculaer și extrem de aglomerat.',
    budget: '3 zile, doi: 900-1.300 €.',
    transport: 'Aeroport FCO – tren Leonardo Express (14 €). Centru – totul pe jos sau metrou (1.50 € călătorie).',
    accommodation: 'Trastevere, Monti sau Pantheon. The Inn at the Roman Forum, Generator Rome.',
    attractions: [
      { name: 'Colosseum + Forum Roman + Palatin', description: 'Bilet combo. Cu ghid – mult mai bun.' },
      { name: 'Vatican (Mus. + Sf. Petru)', description: 'Mergi marțea dimineața devreme. Skip-the-line obligatoriu.' },
      { name: 'Fontana di Trevi', description: 'Mergi noaptea, mai puțină mulțime, lumină magică.' },
      { name: 'Pantheon', description: 'Gratis acum, dar bilet online recomandat.' },
      { name: 'Trastevere seara', description: 'Mâncare și atmosferă autentică romană.' },
    ],
    restaurants: [
      { name: 'Da Enzo al 29', description: 'Cacio e pepe legendar în Trastevere.' },
      { name: 'Roscioli', description: 'Una dintre cele mai bune mese din Roma.' },
      { name: 'Pizzarium', description: 'Pizza al taglio inventată de Gabriele Bonci.' },
    ],
    tips: [
      'Cumpără bilete online la Vatican – eviți cozi de 3h.',
      'Espresso 1.20 € la bar (stand). 4 € la masă.',
      'Café în Piazza Navona – nu, mâncând în lateral 2 strazi.',
      'Du-te la Janiculum Hill pentru cea mai bună panoră.',
    ],
    gallery: [
      'https://images.unsplash.com/photo-1552832230-c0197dd311b5?w=1600',
      'https://images.unsplash.com/photo-1531572753322-ad063cecc140?w=1600',
      'https://images.unsplash.com/photo-1525874684015-58379d421a52?w=1600',
    ],
    publishedAt: '2024-10-20',
  },
]
